version: "2"
plugins:
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 8
    checks:
      squid:S1452:
        enabled: false
  fixme:
    enabled: true
  checkstyle:
    enabled: false
  pmd:
    enabled: true
